[package]
name = "portfolio_rs"
description = "A command line tool for managing financial investment portfolios written in Rust."
readme = "README.md"
version = "0.1.1"
edition = "2021"
license = "MIT" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
clap = "3.2.22"
futures = "0.3.24"
tokio = { version = "1.21.1", features = ["full"] }
yahoo_finance_api = "1.3.0"
piechart = "1.0.0"
