[package]
name = "portfolio_rs"
description = "A command line tool for managing financial investment portfolios written in Rust."
readme = "README.md"
version = "0.1.7"
edition = "2021"
license = "MIT" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.165", features = ["derive"] }
serde_json = "1.0.99"
clap = "4.3.8"
futures = "0.3.27"
tokio = { version = "1.28.2", features = ["full"] }
yahoo_finance_api = "2.0.0"
piechart = "1.0.0"
time = "0.3.22"
chrono = "0.4.26"
sled = "0.34.7"
colored = "2.0.0"
confy = { version = "0.5.1", features = ["yaml_conf"], default-features = false }
